### ISSUE TITLE
Database Manager Icons

### ISSUE THREAD

**Issue by JosephW1993** [stealthbot/StealthBot#1]
The icons are missing from the database manager form.

![image](https://cloud.githubusercontent.com/assets/4599866/14195781/4b57395a-f78b-11e5-9c7d-fdbed2ecfc0b.png)

**Comment by JosephW1993** [comment]
They weren't expand/collapse icons actually... the were single person/group icons.

**Comment by nmbook** [comment]
Hey look at this, someone using the issue tracker!

...I'll do it tomorrow.

**Comment by Davnit** [comment]
This has been fixed in commit https://github.com/stealthbot/StealthBot/commit/6cdb74a7cd8d8d22b7e94830c37b792e789aeb92
