### ISSUE TITLE
Bot does not handle receiving an empty CheckRevision seed

### ISSUE THREAD

**Issue by Davnit** [stealthbot/StealthBot#10]
When using BNLS, the bot will pass the empty string to the BNLS server. Some servers may not handle this either, and cause the bot to get stuck connecting.

When using hashing, a somewhat cryptic message regarding warden is shown, and diagnosing the actual problem can be difficult.

**Comment by Davnit** [comment]
Fixed in https://github.com/stealthbot/StealthBot/commit/f9e095337648ae45c6e570116701c1821bfbe5f8

**Comment by LexManos** [comment]
When is this even a thing?

**Comment by Davnit** [comment]
When you send BNCS a version byte that it doesn't recognize. For example, sending 0x0F for D2DV right now (the current verbyte is 0x0E).
