### ISSUE TITLE
Friends packets handling

### ISSUE THREAD

**Issue by nmbook** [stealthbot/StealthBot#12]
Check whether SID_FRIENDSUPDATE,  SID_FRIENDSADD, SID_FRIENDSREMOVE, and SID_FRIENDSPOSITION are correctly updating the friends list.

I have a suspicion only SID_FRIENDSLIST is causing the actual list to update, even though we fully parse the packets and create internal events. And since I decreased the frequency of getting the list with a change to the way the idle timer works, it's more obvious. Perhaps slightly increase the SID_FRIENDSLIST frequency.

**Comment by Davnit** [comment]
I can confirm that SID_FRIENDSADD and SID_FRIENDSREMOVE do not do anything to the list view. There is code there, but it's commented out. 

SID_FRIENDSPOSITION causes the bot to send SID_FRIENDSLIST (requesting the complete listing).

SID_FRIENDSUPDATE appears to at least try to update the list view.

Also most of the packet ID constants in this area are misnamed.

**Comment by nmbook** [comment]
I think that Stealth researched the friend and clan packets himself, since while they are straightforward, they were probably really new back in 2004 (added for W3) and not really known. But never bothered to complete the handling for the friend internal events, I guess. I don't even know.

**Comment by Davnit** [comment]
The system is even more broken than originally believed. Neither the internal list (g_Friends) or the UI listview are being updated at all except for on receipt of SID_FRIENDSLIST, which isn't being regularly requested for some reason.

**Comment by Davnit** [comment]
Fixed/updated in https://github.com/stealthbot/StealthBot/commit/e74d71f4d4a4ab6ddee1116ab770c98fe09c2373
