### ISSUE TITLE
Diablo II users on open character are displayed as "No stats available" instead of "Open character"

### ISSUE THREAD

**Issue by nmbook** [stealthbot/StealthBot#15]
Also, probably related, logging in to Diablo II characters says "No stats available" instead of the character information.

**Comment by Davnit** [comment]
In my opinion, "no stats available" should only be shown for non-D2 products where the statstring is empty. If the string is not empty, but we consider it "invalid" then it should indicate that the stats are in an unrecognized format. If the only problem is that values are out of range, it should just indicate "unknown" for those values.
