### ISSUE TITLE
Support changing account password

### ISSUE THREAD

**Issue by Davnit** [stealthbot/StealthBot#21]
SID_AUTH_ACCOUNTCHANGE + PROOF and SID_CHANGEPASSWORD

**Comment by nmbook** [comment]
I've been considering supporting the entire account packet range completely using another form, perhaps under Bot > Account Manager. And perhaps it'll even be triggered by "invalid password" and account creation failure. It would be much like how all official clients have separate windows for changing password, resetting password, changing email, and creating a new account. It would have to support interacting with the connection remotely, sort of like what the `/reconnect` command does.

**Comment by nmbook** [comment]
Implemented in f591a7a985d469cf3c0ea85d946ea57518bdac28
