### ISSUE TITLE
Event_ChannelList does not clear the channel list menus

### ISSUE THREAD

**Issue by Davnit** [stealthbot/StealthBot#22]
This results in the entire list being duplicated (both in the bot menu list and the hidden channel-name-blue-bar list) every time SID_CHANNELLIST is received.

**Comment by nmbook** [comment]
It doesn't, but why would you request it again during a connection? I don't think clients ask again when they leave chat for (realms, game, etc).

**Comment by Davnit** [comment]
You can request the list outside of the connection sequence. Regardless of why anyone would do it, if it happens (which is totally possible) the bot doesn't handle it very well.
