### ISSUE TITLE
Add an option for changing DisableSBNews in the UI

### ISSUE THREAD

**Issue by Davnit** [stealthbot/StealthBot#25]
>  [04:04:23.359] <PhiX[BoT]>  [10:04:34.858] To disable version checking, add the line "DisableSBNews=Y" under the [Main] section of your config.ini file.
>  [04:04:31.553] <PhiX[BoT]> why not have a menu or settings entry?

**Comment by nmbook** [comment]
Done in 9d2090c5a360d89e873db06971e0f5b4e3f61e4a.
