### ISSUE TITLE
D2 Realm Logon Cancelled infinite loop + crash

### ISSUE THREAD

**Issue by Davnit** [stealthbot/StealthBot#27]
[Screenshot](http://i.imgur.com/prOyIwp.png)

Happens with config option

> [Features]
> RealmAutoChooseDelay=0

when the account has no characters associated with it (in this case because they expired).

This also results in a short IP ban.

**Comment by nmbook** [comment]
This should be fixed in 8d46458ee47da93f41c87ad3339a87bb67858304, but it still needs more testing.

**Comment by nmbook** [comment]
Should be fixed.
