### ISSUE TITLE
/sdetail overflow (script version numbers)

### ISSUE THREAD

**Issue by nmbook** [stealthbot/StealthBot#3]
If your script defines a version number (Major, Minor, Revision) > 32766, it will overflow the `.sdetail` command.

```
 Script("Major") = 0
 Script("Minor") = 1
 Script("Revision") = 20160323
```

Result of `.sdetail scriptname` of this script:

```
[07:16:57 PM] Error: #6: Overflow in modCommandsInfo.OnScriptDetail().
```

**Comment by Davnit** [comment]
32767 works.

Also version numbers are not release dates.
