### ISSUE TITLE
Could you move the bot functionality to the new version of the program "Visual Studio"?

### ISSUE THREAD

**Issue by iCCupPlatoon** [stealthbot/StealthBot#30]
The question in the subject line. Is it possible?

**Comment by Davnit** [comment]
I made an attempt to do this [here](https://github.com/stealthbot/StealthBot/tree/upgrade), but there are too many differences between VB6 and VB.net to allow for a clean upgrade. Some major functionality would have to be completely redone (the entire scripting system) and a lot of minor things would be completely broken (list view icons, menus, etc).

**Comment by iCCupPlatoon** [comment]
How to be? You're going to try to move the source code to a new platform?

**Comment by Davnit** [comment]
At this time we don't have any plans to move away from VB6. It was proposed several years ago that we do a complete re-write in C#/.NET, but there has been no work towards this since then. If it does happen, the project would still be hosted here.
