### ISSUE TITLE
Windows 10 Support

### ISSUE THREAD

**Issue by RElesgoe** [stealthbot/StealthBot#32]
Has the latest Stealthbot been tested with Windows 10 yet?

**Comment by Davnit** [comment]
Yes, I have been running it on there since Windows 10 came out.

**Comment by RElesgoe** [comment]
I've had to download some .ocx files and place them in the Stealthbot folder, but Stealthbot doesn't recognize `RICHTX32.OCX` in my Stealthbot folder and complains about it when I try to launch a profile. When I run the launcher in compatibility mode as Windows XP SP3, Stealthbot's main screen appears, but attempting to go to Settings -> Bot Settings causes Stealthbot to crash.

I've downloaded and extracted `StealthBot-2.7_Build-489.zip` instead of using the installer, could that be the problem?

**Comment by Davnit** [comment]
Those dependencies aren't loaded from the StealthBot folder, they have to be put in System32 and registered using regsvr32. All of this is done automatically when you use the installer, so if you're having problems I would suggest uninstalling and then reinstalling with the latest version of that.

**Comment by RElesgoe** [comment]
I confirm that the installer works fine, I would suggest making a note in the readme that points the user to some redistributable for VB6.
