### ISSUE TITLE
D2 character statstrings are reported as "Unrecognized stats"

### ISSUE THREAD

**Issue by nmbook** [stealthbot/StealthBot#34]
A change must have occurred with the data in these statstrings on official servers, or something is still wrong involving non-English locales.

**Comment by nmbook** [comment]
It was locales. Fixed in b1dde8bb7516ff47b19436d6234bf929c3793a80.

**Comment by Davnit** [comment]
Should make this default ID (1033) a constant or change the force default setting to just allow a custom value, IMO.

**Comment by nmbook** [comment]
Except 1033 only used for conversions of `Byte()` <-> `String` where the data is not human readable or intended to be (packet buffers, D2 statstrings, etc). I'm not 100% sure that StrConv even uses it for `vbUnicode`/`vbFromUnicode`, besides... (the important part of the conversion is the `vbUnicode`/`vbFromUnicode`).

**Comment by Davnit** [comment]
> Should make this default ID (1033) a constant

It's used in a bunch of places with little explanation. LOCALE_EN_US or something would be fine.
