### ISSUE TITLE
Removing group removes members of that group even if they have their own access

### ISSUE THREAD

**Issue by Davnit** [stealthbot/StealthBot#39]
>  [16:09:32.682] \<Pyro\> .add people 10 --type group
>  [16:09:32.947] \<StealthBot\> people (group) has been given rank 10.
>  [16:09:47.903] \<Pyro\> .add someone 20 --group people
>  [16:09:48.297] \<StealthBot\> someone has been given rank 20, and has been made a member of the group(s): people.
>  [16:09:54.341] \<Pyro\> .add another 20 --group people
>  [16:09:56.109] \<StealthBot\> another has been given rank 20, and has been made a member of the group(s): people.
>  [16:09:57.209] \<Pyro\> .whois someone
>  [16:09:59.343] \<StealthBot\> someone [people (group)] holds rank 20.
>  [16:09:59.434] \<Pyro\> .whois another
>  [16:10:02.672] \<StealthBot\> another [people (group)] holds rank 20.
>  [16:10:05.524] \<Pyro\> .rem people
>  [16:10:06.520] \<StealthBot\> people (group) has been removed from the database.
>  [16:10:10.211] \<Pyro\> .whois someone
>  [16:10:10.625] \<StealthBot\> There was no such user found.
>  [16:10:14.293] \<Pyro\> .whois another
>  [16:10:14.630] \<StealthBot\> There was no such user found.

**Comment by nmbook** [comment]
That is the behavior of the DB Manager too, but it tells you as much in a warning (Yes/No) prompt. It also can be undone since it's not committed until you choose to "Apply and Close".
