### ISSUE TITLE
Reconnect delay should increase on subsequent failures

### ISSUE THREAD

**Issue by Davnit** [stealthbot/StealthBot#43]
Right now it's a static value that is either too long for the occasional "oops my connection went down" or too spammy for when you get IP banned or they are doing server maintenance.

**Comment by nmbook** [comment]
I think reconnect delay needs a bit of work in general: handling more cases (CD-Key ghosting), and there seems to be a couple bugs with it on my build and I don't know if that's my fault or not.

**Comment by nmbook** [comment]
Implemented.
