### ISSUE TITLE
Add support for special user flags (speaker, guest, tournaments, etc)

### ISSUE THREAD

**Issue by Davnit** [stealthbot/StealthBot#5]
Right now it just shows the normal product icons, and there is no indication that these users are special. The product icons should be replaced with the respective flag icon (if such icons are enabled), and the tooltip should show the meaning of these flags instead of the vague "Altered".

A complete listing of the flags can be found [here](https://bnetdocs.org/document/15/chat-flags).

**Comment by nmbook** [comment]
Fixed in 101da55 and 2fe2295

**Comment by nmbook** [comment]
Yes, for now I only added support for those flags currently supported by D1/W2/SC icons.bni, as well as completing support for D1 stats and D1/W2/SC "spawn" icons.

Future:
1. support flags and icons in SC's patch mpq (there's a good number of random tournament icons nobody's ever seen in decades on public servers) - I don't intend to do this as private servers would probably rather use their own art than use other tournaments' art for additional icons, see point 3..
2. support flags and icons in W3 icons-WAR3.bni (mpq with blp contents)
3. support downloading the .bni files and adding those icons dynamically to support private servers
