### ISSUE TITLE
Lag Icons appear incorrectly

### ISSUE THREAD

**Issue by nmbook** [stealthbot/StealthBot#61]
Compared to other bots that use the same icons for "lag" indication, the icons appear improperly. They also appear to lack the color depth they should. The UDP plug in particular appears "cut off", as in the bottom and right rows of pixels appear to be missing.

![StealthBot v2.7_2017-12-16_16-55-19](https://i.imgur.com/T2c4W0m.png)

**Comment by Davnit** [comment]
Done in e9d84e3 and f58525c
