### ISSUE TITLE
Language Script

### ISSUE THREAD

**Issue by pglandrew** [stealthbot/StealthBot#68]
Hello, everyone where i can find a language script? this http://www.stealthbot.net/forum/index.php?/topic/2125-language-translation-script/

is not up anymoore, some one can help?

Regards

**Comment by FiftyToo** [comment]
Can you please stop using this mailing list for scripting questions. I am
sorry that the forum is not as active as it once was, but it is still the
place to go for help.

52

**Comment by pglandrew** [comment]
@FiftyToo mailing? what you mean? with mailing? and where i can ask for script for stealthbot? if not here? since forum is so dead and no one update the links? tell me? maybe give a help with people needs and people dont ask to much, since this is a ISSUE, for stealthbot i need help with it!

PS: STOP BE RUDE! and help people!

Regards
