### ISSUE TITLE
Clan functions not working with new update

### ISSUE THREAD

**Issue by Davnit** [stealthbot/StealthBot#73]
Server updated today 5/1/2018 with new clan size limits and apparently enough little things changed around to where clan functionality is not entirely working.

- Clan member list is not being populated except for updates (SID_CLANMEMBERLIST is not getting a response). Sending the list request after joining chat fixes this.
- ~~g_Clan.InClan is not being set or is not retaining its set state after joining chat. The SID_CLANINFO packet is received (and the event for that is raised along with the message showing the rank and tag).~~

Edit: g_Clan.InClan is fine, it's the Clan object exposed to scripting that doesn't have its properties correctly copied in the Clone() function. That makes this problem a lot easier.

**Comment by visorq** [comment]
I spent 2 days to understand until I found this feature, please fix this in next ver.

**Comment by Davnit** [comment]
Here is a hotfix for clan functionality that should work for the most part.

Just right click on the following link and choose "save link as". Place the ClanHotfix.txt file in your bot's scripts folder (Scripting menu -> Open Script Folder) and then reload scripts (Scripting menu -> reload scripts).

https://gist.githubusercontent.com/Davnit/c138fb2b363e95287727f27095c409e4/raw/4238c902a46cae8d22fe138691d58bee866ae245/ClanHotfix.txt

Also you might need to switch your server to one of the following:
- USEast = connect-use.classic.blizzard.com
- USWest = connect-usw.classic.blizzard.com
- Europe = connect-eur.classic.blizzard.com
- Asia = connect-kor.classic.blizzard.com

**Comment by Davnit** [comment]
This has been patched for build 492 (no estimated release date) and might be fixed sooner by Blizzard.
