### ISSUE TITLE
Event_UserJoins Sub procedure not called

### ISSUE THREAD

**Issue by jqhan** [stealthbot/StealthBot#79]
For scripting, Event_UserJoins doesn't seem to fire off anymore when a user enters a channel. I first witnessed this behaviour about a month ago after a BNET update.

**Comment by Davnit** [comment]
I can't confirm this on the latest build (492). Do you see the normal join message?

```
 [16:43:32] -- Pyro [0ms] has joined the channel using Telnet Chat.
 [16:43:32] UserJoins: Pyro
 [16:44:46] Join/Leave messages disabled.
 [16:44:50] UserJoins: Pyro
 [16:44:55] Join/Leave messages enabled.
```

Test script: 
```vb
Script("Name") = "test"
Script("Author") = "Davnit"

Sub Event_Load()

End Sub

Sub Event_UserJoins(Username, Flags, Message, Ping, Product, Level, Statstring, Banned)
    AddChat Color.White, "UserJoins: " & Username
End Sub
```

**Comment by jqhan** [comment]
Ah, my bad. It only didn't fire off when using the PluginSystem, which I just realized is obsolete...
