### ISSUE TITLE
BNLS fails CheckRevision with Diablo 2 (CheckRevision.mpq)

### ISSUE THREAD

**Issue by pglandrew** [stealthbot/StealthBot#81]
[10:34:33 PM] [BNLS] Error! BNLS has failed CheckRevision. Please check your bot's settings and try again.
 [10:34:33 PM] [BNLS] Product: D2DV.
 [10:34:33 PM] All connections closed.

Diablo 2 Game just was upgrade!

i use 488 build and get this error i try 492 the latest build and still got this error
can some one help to fix it?!

**Comment by Davnit** [comment]
Hmm this seems to be related to the server-side changes they made today. It'll be a while before we can fix it, if we can even fix it. For now though D2 bots probably won't work (regardless of BNLS or local hashing).

**Comment by pglandrew** [comment]
@Davnit any chance to fix this soon?

**Comment by dzik87** [comment]
They changed CheckRevision mpq. It is now CheckRevision.mpq if you use Diablo 2 as client. It will probably take a while before someone reverse it.

**Comment by pglandrew** [comment]
@dzik87 i use Diablo 2, what can i use? warcraft 2 dont have any cd key about that game

i hope team of sb, fix this soon , a lot of people using sb...and is so sad :( to be dead!

**Comment by shalzuth** [comment]
2 viable solutions - 
1 - download and use the CheckRevision.mpq that's downloaded, example code here https://gist.github.com/shalzuth/21d85093d952d197e4f6aa4ba04c92d3
2 - fix check revision, example code here - https://gist.github.com/shalzuth/320d0aecdfd5b788046231a805990147

**Comment by Davnit** [comment]
Thank you @shalzuth! This has been fixed on the BNLS side and I have released a hotfix for StealthBot to make it compatible. You can download it on the [releases page](https://github.com/stealthbot/StealthBot/releases/tag/v2.7-hotfix492).

You will need to replace your current exe with this new one, set your BNLS server to `jbls.davnit.net` and then you should be able to connect.
