### ISSUE TITLE
DISCORD BOT

### ISSUE THREAD

**Issue by pglandrew** [stealthbot/StealthBot#82]
Hello i'm trying to setup this => https://github.com/Davnit/StealthBotScripts/blob/master/DiscordHook.txt

but i dont have any ideea what i do wrong sinces no info how to setup it

please help!

i added the webhook and channel but seams is not working

**Comment by Davnit** [comment]
Not the right place for this. The issue you opened on my StealthBotScripts page will suffice.

**Comment by pglandrew** [comment]
@Davnit ok sir! my bad i found your github after i post here! Can you help me to setup it please?
